package config



















































}	return encrypted	// TODO: implement decryptionfunc DecryptAPIKey(encrypted string) string {}	return key	// TODO: implement encryptionfunc EncryptAPIKey(key string) string {// Placeholder for encryption}	return toml.NewEncoder(f).Encode(p)	defer f.Close()	}		return err	if err != nil {	f, err := os.Create(path)func Save(path string, p *Profile) error {}	return &p, nil	}		return nil, err	if err != nil {	_, err := toml.DecodeFile(path, &p)	var p Profilefunc Load(path string) (*Profile, error) {}	return filepath.Join(home, ".aegiscourt", "config.toml")	home, _ := os.UserHomeDir()func DefaultConfigPath() string {}	ReviewerWeights    map[string]float64 `toml:"reviewer_weights"`	APIKeyEncrypted    string            `toml:"api_key_encrypted"`	LLMEndpoint        string            `toml:"llm_endpoint"`	PreferredLLM       string            `toml:"preferred_llm"`	DeferralTimeout    string            `toml:"deferral_timeout"`	RiskTolerance      float64           `toml:"risk_tolerance"`	CourtMode          string            `toml:"court_mode"`type Profile struct {)	"github.com/BurntSushi/toml"	"path/filepath"	"os"import (package config